kind: pipeline
name: default

steps:
- image: python:3.7-alpine
  name: test
  environment:
    username:
      from_secret: username
    password:
      from_secret: password
  commands:
  - apk add --no-cache build-base git > /dev/null
  - pip install ./src  > /dev/null
  - pip install pytest > /dev/null
  - pytest
- image: python:3.7-alpine
  name: second
  commands:
  - echo ciao